- CONTRIBUTING.md
- package-lock.json
- package.json
- rollup.config.js
> Replace NCC by rollup.js

- .github/workflows/update-index.yml
- .github/workflows/verify.yml
- .gitignore
- stryker.config.json
- Run mutation tests in CI (no mutants allowed)
- Reduce permissions in CI
- Improve CI namings
- Improve `.gitignore`
> Update project configurations

- .github/workflows/verify.yml
- README.md
> Don't use actions/checkout@v1

- .github/codecov.yml
- .github/codeql.yml
- .github/workflows/code-analysis.yml
- .github/workflows/update-index.yml
- .github/workflows/verify.yml
- README.md
- stryker.config.json
- Add code scanning/SAST
- Pin (GitHub Actions) dependencies
- Use `.nvmrc` for NodeJS version
- Only run workflows when necessary
- Start using the [Stryker dashboard (docs)](https://stryker-mutator.io/docs/General/dashboard/) - ([preview](https://dashboard.stryker-mutator.io/reports/github.com/ericcornelissen/git-tag-annotation-action/update-ci#mutant))
- Start using [Codecov](https://codecov.io) - ([preview](https://codecov.io/github/ericcornelissen/git-tag-annotation-action/commit/1c2997bb60f638bf2fefe6a1e95abc86f5e459a9))
- Add status badges to the README
> Update Continuous Integration

- .github/workflows/release.yml
- CONTRIBUTING.md
- README.md
- RELEASE.md
> Initialize the `main-v1` branch

- CHANGELOG.md
- README.md
> Recommend using actions/checkout at v3

- CHANGELOG.md
- src/main.js
- test/main.test.js
Relates to #111
~~Blocked by #138~~
> Deprecate v1 of the Action

- CHANGELOG.md
- package-lock.json
- package.json
Apply #170 to v1 of this action
> [v1] Bump @actions/core from 1.6.0 to 1.7.0

- script/bump-changelog.js
- script/clean.js
> Use `node:` imports in scripts

- index.js
Order imports in all source files. The order that we're aiming for:
1. Builtins
2. Packages (in `node_modules/`)
3. Locals
> Order imports

- CONTRIBUTING.md
- package-lock.json
- package.json
- test/main.test.js
| | a47369502d05d773f2b820bb2cdcb2f8a6eff2f8 | dcb926e43f6ede5e2ee01f12b47947642f2479db |
| --- | --- | --- |
| Test duration | `23.17ms` | `160.43ms` |
> Start property based testing

- .github/workflows/release.yml
- CHANGELOG.md
- RELEASE.md
> Update release process to be sliding branch based

- .github/workflows/verify.yml
> Configure harden-runner for licenses CI job

- CONTRIBUTING.md
Relates to #316. Rewrite and re-order to hopefully improve clarity.
> Update the Contributing Guidelines

- .github/workflows/reusable-audit.yml
Relates to https://github.com/ericcornelissen/git-tag-annotation-action/pull/316
> Rename Gitleaks audit to Secrets audit

- .github/workflows/reusable-audit.yml
> Use audit scripts in reusable audit workflow

- .github/workflows/check.yml
- .gitignore
- CONTRIBUTING.md
- package.json
- stryker.config.js
> General minor changes

- .github/workflows/check.yml
- .github/workflows/nightly.yml
- .github/workflows/reusable-audit.yml
- package-lock.json
- package.json
Aims to address https://github.com/ericcornelissen/git-tag-annotation-action/issues/381
> Add and use better-npm-audit

- package-lock.json
Per https://github.com/ericcornelissen/git-tag-annotation-action/actions/runs/3644926672/jobs/6154620406
> bump (transitive dependency) simple-git from v3.7.1 to v3.15.1

- .github/workflows/check.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/reusable-audit.yml
> Bump CI runner to latest

- .github/workflows/check.yml
- .github/workflows/publish.yml
- CONTRIBUTING.md
- package.json
- script/hooks/pre-commit
- script/hooks/pre-push
See https://github.com/rhysd/actionlint
> Use actionlint to improve CI workflows

- .actrc
> Update `--platform` for act

- .tool-versions
> Add "check out" comment to `.tool-versions`

- .github/workflows/check.yml
- .github/workflows/nightly.yml
- .yamllint.yml
- CONTRIBUTING.md
- Makefile
Relates to #421
Create a (phony) Make target to run [yamllint] using the added config on this project. Also run this command in the "Check / Lint" job to ensure `.yml` files are linted continuously.
[yamllint]: https://github.com/adrienverge/yamllint
> Use yamllint

- .github/workflows/nightly.yml
Relates to #467
Previous attempt didn't quite work as intended. This Pull Request aims to get the initial goal done.
> Reduce tooling update flakiness

- .shellcheckrc
- src/main.sh
Relates to #325
Create the `.shellcheckrc` config file to configure ShellCheck. Configure ShellCheck to enable some "optional" checks that seem to have obvious benefits.
> Enable (some) optional ShellCheck checks

- .github/workflows/check.yml
- .github/workflows/nightly.yml
- .tool-versions
- CONTRIBUTING.md
- Makefile
- src/main.sh
Set up formatting of shell scripts using [shfmt](https://github.com/mvdan/sh).
> Set up shell script formatting

- Makefile
Relates to #501
Re-organize `.PHONY` targets in the `Makefile` for groups of commands to:
1. explicitly group commands, and
2. reduce the line length of `.PHONY` targets
> Refactor the `Makefile`

- .github/workflows/nightly.yml
> Make branch name for tooling updates generic

- README.md
Update the documentation to include a section on security topics. This should help users apply the principle of least privilege more easily.
> Document required permissions and network access

- README.md
Relates to b3de1a802b33ab82ae82fed2df70b2fa52dd1c56, #66, #142
Replace the existing example + known issues section and replace it by a known working example.
> Update known issues, improve full example

- README.md
Relates to #542
Give license paragraph a heading for discoverability.
> Add (explicit) license section to the README

- .github/workflows/check.yml
- .github/workflows/publish.yml
- README.md
Relates to #258, #302
Update workflows based on [the blog post "Four tips to keep your GitHub Actions workflows secure"](https://github.blog/2023-08-09-four-tips-to-keep-your-github-actions-workflows-secure). Review was done manually.
> Harden CI workflow against shell/script injection

- test/security.bats
- test/test.bats
Relates to #577, #586
Remove output file using variable in test setups.
> Remove output file using variable in test setups

- CONTRIBUTING.md
> Remove unused prerequisite Docker

- .editorconfig
- .github/workflows/check.yml
- .hadolint.yml
- .tool-versions
- CONTRIBUTING.md
- Containerfile
- Makefile
> Define an ephemeral development environment container image

- Containerfile
> Remove attribution requirement for dev container
