- .github/workflows/verify.yml
This adds a new job to the CI that runs this Action as [a local action](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-action-in-the-same-repository-as-the-workflow) to verify that it works (more or less) as expected.
Additionally, it splits up the ["Build & Test"](https://github.com/ericcornelissen/git-tag-annotation-action/blob/ec7567cee2fd693a6c2a95eb7d892cc5505fa457/.github/workflows/verify.yml#L8-L26) job into a "Build" job and "Unit Tests" job, where the former no longer works on a matrix of OSs, but just `ubuntu-latest`.
> Add integration test to CI

- .github/workflows/code-analysis.yml
Following this warning from CodeQL outputted by [`github/codeql-action/init@v1.0.24`](https://github.com/ericcornelissen/git-tag-annotation-action/blob/6d2c88c1f1866ef3da96ab537fa0f54f48617b6a/.github/workflows/code-analysis.yml#L29-L33).
> Don't filter by paths `on: push` in code analysis workflow

- script/hooks/common.sh
- script/hooks/pre-commit
- script/hooks/pre-push
Improve the git hooks that were added in #76 (and fixed in #83):
- Update the formatting of `if` statements.
- Don't create stash during merging (which would mess up the merge commit).
- **Do** stash staged changes in the pre-push hook (so the checks run on what's being pushed).
> Improve git hooks

- .github/dependabot.yml
For more information, see [the documentation](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot).
> Enable dependabot updates for GitHub Actions actions

- script/hooks/pre-commit
These should only be committed by the [`update-index.yml` workflow](https://github.com/ericcornelissen/git-tag-annotation-action/blob/623534f482d63b69e3fd78f2dc5d5aa08fdbed4d/.github/workflows/update-index.yml) (possibly a different workflow if #98 gets merged)
> Prevent committing changes in lib/

- .github/workflows/code-analysis.yml
Based on: https://github.blog/2022-04-19-sharing-security-expertise-through-codeql-packs-part-i/
> Add CodeQL pack for GitHub Actions

- index.js
- rollup.config.js
Update the source code to use `node:` imports (see [the docs](https://nodejs.org/api/esm.html#esm_node_imports) for more details) so that these are valid absolute URLs and cannot accidentally be overridden by a third-party dependency.
- I do not plan to backport this change to v1 because I believe those might not work because the `node:` protocol isn't present in most (all?) Node v12 versions (see #111 for context). If anyone thinks it would be possible to use `node:` with the Node v12 runtime, feel free to submit a Pull Request to refactor v1 to use it.
> Use `node:` imports

- CHANGELOG.md
- CONTRIBUTING.md
- src/main.js
- test/main.test.js
Following [the annotation warning](https://github.com/ericcornelissen/git-tag-annotation-action/blob/2ef5e845dd2c6de2e8aeb494610a90f689a05824/src/main.js#L17-L21), this makes changes to the `main-v1` branch to officially end the general support of v1 of this Action.
> Updates for end of general support of v1

- RELEASE.md
Omit the step for "Create a new GitHub Release" for v1 releases. I think no GitHub Release should be created for v1 releases as it messes up the [latest release link](https://github.com/ericcornelissen/git-tag-annotation-action/releases/latest) - i.e. if a v1 release is created after a v2 release, then the latest release link will point to the v1 release, which is not actually the latest release (of interest).
> Update release guidelines for v1

- .github/workflows/deps-analysis.yml
Add a new GitHub Actions workflow for auditing dependencies. It is scheduled weekly for an initial trail, and audits dependencies on both `main` and `main-v1`. The latter is especially of interest, as it a failed job would alert about problems on v1 that are not present on v2 (since `npm audit` exits with a non-zero exit code if a problem is detected). The former is more-or-less already covered by Dependabot, nevertheless, it's there for completeness.
> Add scheduled workflow to audit dependencies

- package-lock.json
Update to a version of terser that's not vulnerable to ReDoS - per https://github.com/ericcornelissen/git-tag-annotation-action/actions/runs/2725681098
> Update terser (v1)

- .github/workflows/verify.yml
- CHANGELOG.md
- action-types.yml
- action.yml
Add support for usage of this Action with [GitHub Actions Kotlin DSL](https://github.com/krzema12/github-actions-kotlin-dsl) by adding a `action-types.yml` file with type definitions for Action inputs and outputs.
Also, use the [GitHub Actions Typing Action](https://github.com/krzema12/github-actions-typing) to validate the validity of this `action-types.yml` file.
> Add support for GitHub Actions Kotlin DSL

- .fossa.yml
Primarily to exclude the bundled files in the `lib/` folder from being included in the analysis.
> Add a configuration file for Fossa

- .github/workflows/check.yml
- CHANGELOG.md
- package-lock.json
- package.json
Reverts ericcornelissen/git-tag-annotation-action#326 given the failing build on 93ea7a5c024abd787bc787018799cf882a42cb5b
Reverts ericcornelissen/git-tag-annotation-action#330 given that failing build wasn't detected in ericcornelissen/git-tag-annotation-action#326 as a result of running the tests on the `main` branch instead of the PR branch (because apparently that's how `pull_request_target` works :sweat_smile:)
> Revert 2 pull requests

- CHANGELOG.md
- package-lock.json
- package.json
- rollup.config.js
> Bump @actions/core from 1.9.1 to 1.10.0

- .github/workflows/reusable-audit.yml
- CONTRIBUTING.md
- package.json
Create two new npm scripts/commands for auditing dependencies and auditing only production dependencies. These (still) work using `npm audit`.
The reasoning behind adding these is that it gives a permanent command that can have a changing underlying implementation over time. Making contributors remember less as well as allowing for things such as having different auditing mechanisms for different refs use the same CI workflow (e.g. v2, v3, and `main`).
> Create "audit" commands

- .github/workflows/check.yml
Closes #324
---
Replace downloading the Fossa CLI in the CI by using the [Fossa Action](https://github.com/fossas/fossa-action). Hopefully this will address some timeout issues we've experienced in the CI due to the `fossa test` call taking too long (**EDIT**: welp, [it doesnt...](https://github.com/ericcornelissen/git-tag-annotation-action/actions/runs/3277163463/jobs/5394086883)). Unfortunately this still relies on the Fossa API secret, with all associated drawbacks.
> Update license check in CI to use the Fossa Action

- .github/workflows/release.yml
- Updated deprecated `set-output` feature in `release` workflow.
- Closes #359
> Update deprecated set-output feature in release workflow

- .c8rc.json
- package.json
Move the c8 configuration from `package.json` (CLI args) into a dedicated c8 configuration file, reference the configuration file explicitly to aid with understanding for anyone unfamiliar with c8.
On top of what was already configured, configure what should files should be considered for coverage an minimum coverage thresholds.
> Create c8 configuration file

- .github/workflows/check.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/reusable-audit.yml
Update all GitHub Actions workflows to use a specific runner image for all jobs. The chosen images are based on what the documented `latest` images are on December 9, 2022. Upgrading to more recent images may be done separately.
Doing this should help with reproducability. It's currently not known if Dependabot will keep these up-to-date automatically, but since upgrades for these are generally uncommon manually keeping them up-to-date should be doable.
> Pin all runner images in GitHub Actions workflows

- .github/workflows/check.yml
- .tool-versions
Relates to #421
---
Create a `.tool-versions` file with currently untracked dependencies (that we want to track). This file is first a configuration format for [asdf], but is also human-readable and thus can be used to know and track what versions of dependencies _should_ be used.
[asdf]: https://asdf-vm.com/
> Add `.tool-versions`

- package.json
Relates to #384, #421
Change the `lint:docker` command details to run from a version tag instead of an image hash. Image hashes are tied to the target architecture, making it inconvenient for this particular use case. Switching to a version tag still provides good reproducibility guarantees (it can be expected that a version isn't re-published) - in contrast to an image hash which provides better reproducibility guarantees (it makes re-publishing cryptographically difficult) and by extension more secure.
> Pin hadolint to a version (instead of hash)

- .tool-versions
Relates to #421, #435
Bump ShellCheck from `0.8.0` to `0.9.0`.
> Bump ShellCheck to latest

- .github/workflows/publish.yml
Update the publishing workflow to automatically generate signatures for releases using [cosign](https://github.com/sigstore/cosign)'s [keyless signing](https://github.com/sigstore/cosign/blob/5282e31994cf8c02a6a0a07236a3c46f224b3322/KEYLESS.md).
> Sign releases using cosign

- .github/workflows/nightly.yml
Relates to #421 
Create a GitHub Actions workflow to update tooling nightly. This workflow will use asdf to install the latest version of each tool, update the `.tool-versions` file if necessary, and create a Pull Request to update the tool (if there's any changes).
> Keep tooling up-to-date

- .github/workflows/publish.yml
Relates to #436, #459
Was set to audit after adding release signing. Re-setting to block after having run the job to release v2.0.6. See also https://app.stepsecurity.io/github/ericcornelissen/git-tag-annotation-action/actions/runs/3828526299
> Configure harden-runner for "Publish / GitHub"

- .github/workflows/nightly.yml
Relates to #461
Update the nightly workflow's tooling update job to automatically retry the flaky step of getting the latest available version of the tool using [`nick-fields/retry`]. Since the duration of this job doesn't matter much, and to be on the safe side, a timeout of 1 minute is configured to increase the probability of success.
Since the outputs of [`nick-fields/retry`] are restricted, the latest version is now stored as an [environment variable](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions).
[`nick-fields/retry`]: https://github.com/nick-fields/retry
> Reduce tooling update flakiness

- .github/workflows/nightly.yml
Relates to #461 (improvement)
Relates to #467 (revert job name removal)
Add and configure harden-runner for the (nightly) tooling updates job.
See runs:
- https://github.com/ericcornelissen/git-tag-annotation-action/actions/runs/3877656840
- https://github.com/ericcornelissen/git-tag-annotation-action/actions/runs/3877754639
> Add harden-runner to tooling updates job

- .github/workflows/publish.yml
Separate concerns. Also reduce scope of `id-token` permission
> Separate git and GitHub (Release) job for publishing

- .github/workflows/check.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
- .tool-versions
Relates to #421, #448
Keep the version of `cosign` used by this project tracked by storing it in the `.tool-versions` file.
> Add `cosign` to .tool-versions

- .github/workflows/nightly.yml
Relates to  #470
Increase retry wait time. 30 seconds proved to not be sufficient for getting success on the second try, trying 2 minutes now. Also reduce the timeout to 20 seconds, in general, if successful, this steps takes only a couple of seconds.
See also https://github.com/ericcornelissen/git-tag-annotation-action/actions/runs/3908028622/attempts/1
> Adjust retry timings for getting latest version of tools

- .github/workflows/check.yml
- .github/workflows/nightly.yml
- .tool-versions
- CONTRIBUTING.md
Relates to #421, #462
Add [yamllint](https://github.com/adrienverge/yamllint) to `.tool-versions` and use [ericcornelissen/asdf-yamllint](https://github.com/ericcornelissen/asdf-yamllint). Set it to `1.28.0` because that's the version I had installed locally.
> Add yamllint to `.tool-versions`

- CONTRIBUTING.md
- Makefile
Add two new [Make](https://www.gnu.org/software/make/) targets for contributor convenience:
1. `lint`: to run all lint targets
2. `verify`: to run most verification targets (e.g. lint and test) to quickly validate changes are correct.
> Create convenience Make targets for change verification

- .github/workflows/check.yml
- .github/workflows/nightly.yml
Relates to #462, #479 
Simplify the tooling setup with [asdf](https://asdf-vm.com/) in CI. Remove the now-unnecessary explicit setup of the [yamllint plugin](https://github.com/ericcornelissen/asdf-yamllint).
> Update tooling setup in CI

- .github/workflows/check.yml
- .github/workflows/nightly.yml
Relates to #148
Allow call to `sigstore-tuf-root.storage.googleapis.com:443` in workflows. It's already allowed in `publish.yml`, now also in other workflows as it's being called out to when cosign is being installed.
> Update CI egress policy

- Makefile
Followup to #497
#497 added two new targets but forgot to mark those targets as `.PHONY`.
> Add missing phony targets to `Makefile`

- .github/workflows/nightly.yml
Relates to #467
Remove the dependency on `nick-fields/retry` as retrying does not seem to help much to avoid job failures (which was the original motivation for using it).
> Update the automatic tooling update job

- .github/workflows/check.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
Relates to #535
Since using cosign 2.0.2 jobs installing tooling use a new endpoint during installation.
> Update egress policies for CI jobs installing tooling with asdf

- .github/workflows/check.yml
Relates to #511
Remove the CI job that runs [Semgrep](https://semgrep.dev/) from the project. The primary reason for this is to reduce the number of project dependencies. While Semgrep works pretty well and isn't noisy, it doesn't add too much to this project at the moment.
> Drop Semgrep dependency

- .github/workflows/nightly.yml
- .github/workflows/release.yml
Relates to #397, #460
Rename `RELEASE_APP_ID` and `RELEASE_APP_PRIVATE_KEY` to `AUTOMATION_APP_ID` and `AUTOMATION_APP_PRIVATE_KEY` as these aren't used for release purposes exclusively.
> Rename secrets for automation purposes

- test/security.bats
- test/test.bats
Relates to #577
Update the tests to be POSIX compliant so that they run (out of the box) on more systems.
> Make tests POSIX compliant

- .github/workflows/check.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
Relates to #559
Update CI workflows containing embedded shell scripts to be formatted the same as `.sh` files.
> Format shell scripts in CI workflows the same as `.sh` files

- .github/dependabot.yml
Relates to #40, #95, #577
Update the Dependabot configuration to keep the git submodules up-to-date. I believe the directory should be `/` because `.gitmodules` is at the project root. Set to a monthly cadence because I currently believe keeping these up-to-date on a more regular basis isn't necessary.
Values are based on [the Dependabot documentation (accessed August 7, 2023)](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file).
> Configure Dependabot to update git submodules

- test/security.bats
- test/test.bats
Relates to #577
Add assertions for success and `stdout` to all tests. (As far as I can tell bats-core doesn't allow you to make assertions about stderr.)
> Assert success and `stdout`

- script/bump-changelog.mjs
- script/bump-version.mjs
- script/get-release-notes.mjs
Relates to #511
- Naming and ordering.
- Import formatting using `* as`.
- Erroring using `throw new Error()`.
- Fix unknown variable in bump-version script.
> Refactor scripts for consistency

- README.md
- Bump version of `actions/checkout` used in docs.
- No other external actions are present in the docs of this project.
> bump version of actions/checkout used in docs

- .actrc
- .tool-versions
- CONTRIBUTING.md
- Makefile
Relates to #226
Supersedes #603
The reason is twofold:
1. To reduce dependencies for this relatively inactive project to reduce maintenance burden.
2. There's a test suite that can be run locally.
And, of course, it's still possible to run the e2e tests using `act` - it's just the explicit dependency and basic configuration that are gone.
> Drop dev dependency on `act`

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- RELEASE.md
- SECURITY.md
- script/bump-changelog.mjs
- script/bump-version.mjs
- script/get-release-notes.mjs
- src/main.sh
- test/test_functional.sh
- test/test_security.sh
Relates to #542, #579
Add SPDX license identifiers to relevant (non-configuration and not-already-licensed) files to indicate, at the file level, what license applies. This is partially useful for anyone that (somehow) only has access to part of the project, but in the case of some files it actually clarifies the intended license.
> Adopt SPDX license identifiers for file-level license details

- .github/workflows/check.yml
- README.md
Relates to #420
Update the e2e test matrix to test against all currently supported runner images. Relatedly, add sections to the various documentation that these runner images are tested and thus recommended.
> Run e2e tests on more runner images

- README.md
Relates to #542, #649
Remove copyleft-like share-alike requirement for the docs, aligning it with the more permissive MIT license used for the code in this project.
> Align docs license with code license

- Makefile
Add an explicit license to the `Makefile`.
> Make `Makefile` license explicit

- .github/workflows/publish.yml
Closes #475
Relates to #674
Relates to ["Publish / GitHub" run `8270547728`](https://github.com/ericcornelissen/git-tag-annotation-action/actions/runs/8270547728)
> Configure egress policy for publish workflow
